---
apiVersion: v1
kind: Namespace
metadata:
  # Feel free to select another namespace name
  name: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express-app
  name: express-app
  namespace: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - image: fvilers/sample-express-app:1.0.0
          name: express-app
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-app
  name: express-app
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: express-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: express-app
  namespace: sample
spec:
  rules:
    # Set this to your cluster node IP
    - host: express-app.192.168.1.174.nip.io
      http:
        paths:
          - backend:
              serviceName: express-app
              servicePort: http
            path: /
  tls:
    - hosts:
        # Set this to your cluster node IP
        - express-app.192.168.1.174.nip.io
