name: Build and push Docker image to Docker Hub
on:
  push:
    tags:
      - v*
jobs:
  build_and_push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract metadata for Docker
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: fvilers/sample-express-app
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images with Buildx
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
